#!/bin/sh
# fakeroot load-test
#
# This test tests if fakeroot breaks under load, especially ordering
# of calls between different processes.
#
# Copyright (c) 2009 Eduardo Habkost <ehabkost@raisama.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -e

tmp="$1"

chmod_flood()
{
	while :;do
		chmod 0777 $tmp/dummy.$1.*
		chmod 0600 $tmp/dummy.$1.*
	done
}

create_dummy_files()
{
	echo Creating dummy files:
	for t in `seq 1 $threads`;do
		for n in `seq 1 $files`;do
			touch $tmp/dummy.$t.$n
		done
		echo -n .
	done
	echo
}

start_flooding()
{
	pids=
	echo Creating flooder threads:
	for t in `seq 1 $threads`;do
		chmod_flood $t 2>/dev/null &
		pids="$pids $!"
		echo -n .
	done
	echo
	trap terminate_threads EXIT INT
}

terminate_threads()
{
	[ -n "$pids" ] && kill $pids
	wait
	pids=
}


mkdir -p "$tmp"

threads=2
files=20

create_dummy_files
start_flooding

set -x


touch $tmp/testfile

mkfifo $tmp/replies

./timedchown 10 20 $tmp/testfile 1000 1000 $tmp/replies \
	| ./timedstat $tmp/testfile $tmp/replies

terminate_threads
exit 0
